# Generated by Django 4.2 on 2023-11-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_chatmess'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='check_admin_user',
            field=models.BooleanField(default=False),
        ),
    ]
